/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MiGallery {
        /**
          * @public 
          * @property items
          * @type {Array<any>}
          * @memberof ImageGalleryComponent
         */
        "items": Array<any>;
    }
    interface MiImage {
        /**
          * @public 
          * @property description
          * @type {string}
          * @memberof ImageComponent
         */
        "description": string;
        /**
          * @public 
          * @property heading
          * @type {string}
          * @memberof ImageComponent
         */
        "heading": string;
        /**
          * @public 
          * @property image
          * @type {string}
          * @memberof ImageComponent
         */
        "image": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMiGalleryElement extends Components.MiGallery, HTMLStencilElement {
    }
    var HTMLMiGalleryElement: {
        prototype: HTMLMiGalleryElement;
        new (): HTMLMiGalleryElement;
    };
    interface HTMLMiImageElement extends Components.MiImage, HTMLStencilElement {
    }
    var HTMLMiImageElement: {
        prototype: HTMLMiImageElement;
        new (): HTMLMiImageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mi-gallery": HTMLMiGalleryElement;
        "mi-image": HTMLMiImageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MiGallery {
        /**
          * @public 
          * @property items
          * @type {Array<any>}
          * @memberof ImageGalleryComponent
         */
        "items"?: Array<any>;
    }
    interface MiImage {
        /**
          * @public 
          * @property description
          * @type {string}
          * @memberof ImageComponent
         */
        "description"?: string;
        /**
          * @public 
          * @property heading
          * @type {string}
          * @memberof ImageComponent
         */
        "heading"?: string;
        /**
          * @public 
          * @property image
          * @type {string}
          * @memberof ImageComponent
         */
        "image"?: string;
        /**
          * @public 
          * @property onSelection
          * @type {EventEmitter}
          * @memberof ImageComponent
         */
        "onSelection"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mi-gallery": MiGallery;
        "mi-image": MiImage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mi-gallery": LocalJSX.MiGallery & JSXBase.HTMLAttributes<HTMLMiGalleryElement>;
            "mi-image": LocalJSX.MiImage & JSXBase.HTMLAttributes<HTMLMiImageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
